"""
Django settings for back_jn project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&%a9i_--@jj-ip%mnf&%1@cvt#orh$p#o^i=u-pi@h87#@f%ym'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'back_jn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'back_jn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import sys

# Detecta se estamos rodando “manage.py test”
TESTING = 'test' in sys.argv

DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.postgresql',
        'NAME':     'postgres',
        'USER':     'postgres.izyxzlthhlkryttmfzga',
        'PASSWORD': 'yY6sE2weOj2DtYiG',
        'HOST':     'aws-0-us-east-1.pooler.supabase.com',
        'PORT':     '6543',
        'TEST': {
            'NAME': 'test_postgres',
        },
        'OPTIONS': {
            # Aqui você inclui **todas** as schemas com tabelas de negócio
            'options': '-c search_path=aprendizagem,auth,certificado,gamific,premios,progresso,public,realtime,storage,usuario'
        },
    },
    # DB extra só para inspectdb
    'introspect': {
        'ENGINE':   'django.db.backends.postgresql',
        'NAME':     'postgres',
        'USER':     'postgres.izyxzlthhlkryttmfzga',
        'PASSWORD': 'yY6sE2weOj2DtYiG',
        'HOST':     'aws-0-us-east-1.pooler.supabase.com',
        'PORT':     '6543',
        'OPTIONS': {
            'options': '-c search_path=aprendizagem,auth,certificado,gamific,premios,progresso,public,realtime,storage,usuario'
        },
    },
}

if TESTING:
    # usa sqlite in-memory nos testes
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
    # força syncdb para o app core (sem migrações)
    MIGRATION_MODULES = {
        'core': None,
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

from datetime import timedelta

SIMPLE_JWT = {
    # seus outros ajustes…
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

    # <<< ativa o update automático de last_login no usuário
    'UPDATE_LAST_LOGIN': True,
}
# Configurações do Amazon S3 e keys
#isso nao é seguro, mas é para fins de estudo!!!!!!!!!!!
AWS_ACCESS_KEY_ID = 'AKIAYKN45N4R7CQIRDV7'
AWS_SECRET_ACCESS_KEY = "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"
AWS_STORAGE_BUCKET_NAME = 'jotanunes-videos'
AWS_REGION_NAME = 'us-east-2'

OPENAI_API_KEY = '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'