# Generated by Django 5.1.7 on 2025-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_cpf_user_matricula_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricula',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
