# Generated by Django 5.1.7 on 2025-03-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('duracao', models.DurationField(blank=True, null=True)),
                ('link', models.URLField()),
                ('legenda', models.TextField(blank=True, null=True)),
                ('transcricao', models.JSONField(blank=True, null=True)),
                ('id_quiz', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
