# Generated by Django 5.1.7 on 2025-03-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguntas', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.video')),
            ],
        ),
    ]
